version: '3.8'

services:
  api-users:
    build: 
      context: ./api-users
      dockerfile: Dockerfile
    volumes:
      - ./api-users/data:/usr/src/app/data
    restart: always

  api-posts:
    build: 
      context: ./api-posts
      dockerfile: Dockerfile
    volumes:
      - ./api-posts/data:/usr/src/app/data
    restart: always

  api-matchmaker:
    build: 
      context: ./api-matchmaker
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
    depends_on:
      - api-users
    restart: always

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    environment:
      - PORT=8600
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
      - POSTS_SERVICE_URL=${POSTS_SERVICE_URL}
      - MATCHMAKER_SERVICE_URL=${MATCHMAKER_SERVICE_URL}
    depends_on:
      - api-users
      - api-posts
      - api-matchmaker
    restart: always

  # --- OBSERVABILITY STACK ---

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability
    restart: always

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
      - ./monitoring/loki/data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability
    restart: always

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - observability
    restart: always

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
    - ./monitoring/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - observability
    restart: always

networks:
  observability:
    driver: bridge
