version: '3.8'

services:
  api-users:
    build: 
      context: ./api-users
      dockerfile: Dockerfile
    volumes:
      - ./api-users/data:/usr/src/app/data
    restart: always

  api-posts:
    build: 
      context: ./api-posts
      dockerfile: Dockerfile
    volumes:
      - ./api-posts/data:/usr/src/app/data
    restart: always

  api-matchmaker:
    build: 
      context: ./api-matchmaker
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
    depends_on:
      - api-users
    restart: always

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    environment:
      - PORT=8600
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
      - POSTS_SERVICE_URL=${POSTS_SERVICE_URL}
      - MATCHMAKER_SERVICE_URL=${MATCHMAKER_SERVICE_URL}
    depends_on:
      - api-users
      - api-posts
      - api-matchmaker
    restart: always
