apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-matchmaker
  labels:
    app: api-matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-matchmaker
  template:
    metadata:
      labels:
        app: api-matchmaker
    spec:
      containers:
      - name: api-matchmaker
        image: pipatchies/flateurss-api-matchmaker:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: USERS_SERVICE_URL
          value: "http://api-users:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: api-matchmaker
spec:
  selector:
    app: api-matchmaker
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: NodePort # Exposed for access
