apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-posts
  labels:
    app: api-posts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-posts
  template:
    metadata:
      labels:
        app: api-posts
    spec:
      containers:
      - name: api-posts
        image: pipatchies/flateurss-api-posts:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
---
apiVersion: v1
kind: Service
metadata:
  name: api-posts
spec:
  selector:
    app: api-posts
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
