apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users
  labels:
    app: api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
      - name: api-users
        image: pipatchies/flateurss-api-users:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: api-users
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
