global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8600']

  - job_name: 'api-users'
    static_configs:
      - targets: ['api-users:3001']

  - job_name: 'api-posts'
    static_configs:
      - targets: ['api-posts:3002']

  - job_name: 'api-matchmaker'
    static_configs:
      - targets: ['api-matchmaker:3003']
